"""create community tables

Revision ID: 9d1340299d64
Revises: 2b73189dbe63
Create Date: 2026-08-25 00:08:02.297110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1340299d64'
down_revision: Union[str, Sequence[str], None] = '2b73189dbe63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active_members_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communities_id'), 'communities', ['id'], unique=False)
    op.create_index(op.f('ix_communities_name'), 'communities', ['name'], unique=True)
    op.create_table('community_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_memberships_community_id'), 'community_memberships', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_memberships_id'), 'community_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_community_memberships_user_id'), 'community_memberships', ['user_id'], unique=False)
    op.create_table('assessment_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.String(length=50), nullable=False),
    sa.Column('languages_known', sa.String(length=255), nullable=False),
    sa.Column('problem_solving_comfort', sa.String(length=50), nullable=False),
    sa.Column('main_goal', sa.String(length=100), nullable=False),
    sa.Column('weekly_time_commitment', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['community_memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id')
    )
    op.create_index(op.f('ix_assessment_data_id'), 'assessment_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_data_id'), table_name='assessment_data')
    op.drop_table('assessment_data')
    op.drop_index(op.f('ix_community_memberships_user_id'), table_name='community_memberships')
    op.drop_index(op.f('ix_community_memberships_id'), table_name='community_memberships')
    op.drop_index(op.f('ix_community_memberships_community_id'), table_name='community_memberships')
    op.drop_table('community_memberships')
    op.drop_index(op.f('ix_communities_name'), table_name='communities')
    op.drop_index(op.f('ix_communities_id'), table_name='communities')
    op.drop_table('communities')
    # ### end Alembic commands ###
